print("Navin PAudel")
print('\n')
print("My full Adress is ")
print('\n')
print("Distric: ","Dang")
print('\n')
print("Municipality/VDC: ","Tulsipur-17")
print('\n')
print("Education :"+"Bacheoler running")
print('\n')
print("my age is ",23)
print('\n')
print("my contact number is"+ str(9860163196))